### ISSUE TITLE
iOs wont open file

### ISSUE THREAD

**Issue by rfcabal** [pwlin/cordova-plugin-file-opener2#167] opened 2017-09-10 15:29 UTC
Hi Guys

I'm using this plugin to open a file which I downloaded, here is my code:

```
// Crear nueva transferencia
var fileTransfer = new FileTransfer();
// URL de descarga del archivo
var uri = encodeURI($scope.folder + filename);
// Ruta de donde se descargará el archivo
var filePath = cordova.file.documentsDirectory + filename;

// Descarga de archivo
fileTransfer.download(
uri,
filePath,
function(entry) {

    console.log("download complete: " + entry.toURL());

    // Cambio de estado a descargado
    $scope.download = 2;

    // Abrir el archivo en APP
    cordova.plugins.fileOpener2.showOpenWithDialog(

        cordova.file.documentsDirectory + filename, // Dirección de arhivo la misma que descarga
        'application/pdf', // Tipo MIME del archivo para relacionarlo con aplicaciones
        {
            error: function(e) {
                console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
            },
            success: function() {
                console.log('file opened successfully');
            }
        }
    );

},
function(error) {
    // Estado de archivo no descargado.
    $scope.download = 3;
    // Error en consola.
    console.log("download error source " + error.source);
    console.log("download error target " + error.target);
    console.log("download error code" + error.code);
},
false, {
    //headers: {
    //    "Authorization": "Basic dGVzdHVzZXJuYW1lOnRlc3RwYXNzd29yZA=="
    //}
}
);
```

It's downloading my file but once is looking for the file to open it, it does nothing.

This is the log from ios simulator
![2017-09-10_122530](https://user-images.githubusercontent.com/5440128/30250354-3bccbec8-9623-11e7-96fb-30308fa5daf1.png)

I was looking for the file in a terminal and the file exist
![2017-09-10_122700](https://user-images.githubusercontent.com/5440128/30250368-620dc082-9623-11e7-98d8-7ed5cf684018.png)

I saw this #2  and I use the solution but doesn't work for me

**Comment by andycaoz4** [comment] 2017-09-18 07:43
I am also running into this issue as well with 'showOpenWithDialog' in iOS. Standard open method works fine, but showopenwithdialog shows nothing. Console says file was opened successfully nevertheless.

What I've tried: file-opener2 ver 2.0.19 on actual iPad Mini.
My file path is: /var/mobile/Containers/Data/Application/499541BB-838D-4E9B-8C21-DF23BBE24FB0/Documents/Library/NoCloud/sleeping-fat-cat.jpg

I used entry.toURL(),

Tried both add/remove in config.xml <preference name="iosPersistentFileLocation" value="Library" />, didn't fix anything in either case.

Tried both 
NSURL *fileURL = [NSURL URLWithString:path]; <--- open file success, but no showopendialogue
NSURL *fileURL = [NSURL fileURLWithPath:path]; <--- error out file does not exist

**Comment by fpoirier1** [comment] 2017-10-03 14:50
+1

**Comment by andycaoz4** [comment] 2017-10-03 15:40
@fpoirier1, I got it to work from the solutions on 145. It seems the dialog window is indeed showing, but the position was off screen for whatever reason.

https://github.com/pwlin/cordova-plugin-file-opener2/issues/145

**Comment by fpoirier1** [comment] 2017-10-03 17:23
Awesome thanks !

**Comment by darylldawn** [comment] 2018-04-27 07:36
@fpoirier1 Did #145 helped you? Or did you use another solution?

Thanks!

**Comment by shnist** [comment] 2018-12-12 10:31
possible duplicate of https://github.com/pwlin/cordova-plugin-file-opener2/issues/145, which may be resolve by this PR https://github.com/pwlin/cordova-plugin-file-opener2/pull/72

**Comment by shnist** [comment] 2018-12-17 11:54
closing as duplicate

**Closed by shnist** 2018-12-17 11:54 UTC
Labels: bug
