### ISSUE TITLE
iOS open ambiguous apps 

### ISSUE THREAD

**Issue by gaohuasheng** [pwlin/cordova-plugin-file-opener2#103] opened 2017-03-14 02:45 UTC
Hello, when I open .jpg file with file-opener2, I got a icon list on my iphone screen, but most of them can't open it, only can transfer to others. How can I just show apps that only open .jpg file.
![mmexport1489459415993](https://cloud.githubusercontent.com/assets/6946280/23883625/46f2828c-08a3-11e7-8363-df574180158d.jpg)

**Comment by ferdelcorro** [comment] 2017-03-28 17:26
Same problem here!

**Comment by Gillardo** [comment] 2017-04-04 18:01
That was the fix that I applied but someone undone it saying it didn't work!! Have a look at PRs and u will see what needs reapplying

**Comment by vzharkov** [comment] 2017-04-05 12:58
@Gillardo thanks for advice. I have tried to use code from your PR, but it leads to "the file is not exists" error.

**Comment by Gillardo** [comment] 2017-04-05 13:22
You changed `NSURL *fileURL = [NSURL URLWithString:path];` to `NSURL *fileURL = [NSURL fileURLWithPath:path];`??

**Comment by vzharkov** [comment] 2017-04-05 13:46
When I use `NSURL *fileURL = [NSURL URLWithString:path];` it generates `"nativeURL":"file:///var/mobile/Containers/Data/Application/...` path and it trying to open with the dialog above.
When I use `NSURL *fileURL = [NSURL fileURLWithPath:path];` it generates `file:/var/mobile/Containers/Data/Application/...` path and leads to `File does not exist`

I am is beginner in IOS. Is the dialog at the screenshot above a correct plugin behavior? I just expect to see the image preview like it works in the Android plugin.

**Comment by vzharkov** [comment] 2017-04-05 13:59
@Gillardo I just try to install this fork https://github.com/Arxi/cordova-plugin-file-opener2 and it works perfect. I found it in this issue #73 
I think this fork should be merged to master branch by PR.

**Comment by pwlin** [comment] 2017-04-05 16:05
> I think this fork should be merged to master branch by PR.

Yes it should! The problem is that no one bothered to send me a PR for that changeset! If you look at the same issue you mentioned, you will notice that I begged everyone to send me a PR so I can merge it but at the end, no one did! This plugin is a community effort and any contribution has been always welcomed. Unfortunately not everyone sends a PR for their changes and when I beg them to do, they just ignore me!

@Gillardo  I can't remember anymore why I have reverted your changes. I think some other users  complained it broke their app. It was a mistake and I apologize. I re-added your changes now and pushed a new version (`2.0.10`) to `npm`.

**Comment by vzharkov** [comment] 2017-04-06 06:18
@pwlin as I wrote above https://github.com/pwlin/cordova-plugin-file-opener2/commit/69099524c57ea00593bbc4014f7890c1b41b83ce commit leads to error on IOS10.

I'll make PR for solution from Arxi asap.

**Comment by vzharkov** [comment] 2017-04-06 06:30
@pwlin and I think the comment above need to be reverted again 😄

**Comment by pwlin** [comment] 2017-04-06 13:04
@vzharkov no problem I already did 😄 please see #107

**Comment by pwlin** [comment] 2017-04-06 13:59
Thanks to the PR from @vzharkov, there is a new version (`2.0.11`) which fixes the problems mentioned in this issue. Please upgrade.

**Closed by pwlin** 2017-04-06 13:59 UTC
