### ISSUE TITLE
Error "looking for file at (null)" when using german umlauts in the file name

### ISSUE THREAD

**Issue by tillsanders** [pwlin/cordova-plugin-file-opener2#252] opened 2019-02-27 13:16 UTC
### Expected Behaviour

When opening a pdf like so, I would expect the pdf to be opened ;)

```javascript
cordova.plugins.fileOpener2.open(
  "file:///var/mobile/Containers/Data/Application/{...}/Library/NoCloud/ümlaut.pdf",
  'application/pdf',
  {
    error: () => reject(new Error('Error while opening file.')),
    success: () => resolve(),
  },
);

### Actual Behaviour

The error callback is executed and a message in XCode appears:

`looking for file at (null)`

When not using umlauts (ä, ö, ü) in the file name, it works as expected.

### Reproduce Scenario

#### Platform and Version

Tested with:

- cordova-plugin-file-opener2 2.2.0
- XCode 10.1
- cordova 8.1.1
- cordova-ios 4.5.5
- iOS 12.1.2

Other plugins: 

- cordova-plugin-file
- cordova-plugin-statusbar
- cordova-plugin-whitelist

**Comment by shnist** [comment] 2019-03-01 16:41
hi @tillsanders thanks for raising this issue. Will take a look.

**Comment by shnist** [comment] 2019-03-01 16:42
as a reference, this issue has been around for a while https://github.com/pwlin/cordova-plugin-file-opener2/issues/190. thought it was resolve in 2.2.0, but obviously not.

**Comment by shnist** [comment] 2019-04-23 09:30
Going to close this ticket as a duplicate of https://github.com/pwlin/cordova-plugin-file-opener2/issues/190

**Closed by shnist** 2019-04-23 09:30 UTC
