### ISSUE TITLE
Can the fileMIMEType variable be left blank

### ISSUE THREAD

**Issue by Xufj1025** [pwlin/cordova-plugin-file-opener2#213] opened 2018-06-01 08:33 UTC
Because I'm not sure what type of file I want to open, can I open this parameter without filling it out?

**Comment by cmartin81** [comment] 2018-06-04 11:28
You can try the following:
add mime-types to your project

    import {lookup} from 'mime-types';
    ....
    ....
    await this.fileOpener.open(fileUrl, lookup(fileUrl));

**Comment by shnist** [comment] 2018-12-13 11:02
hi @Xufj1025 , thanks for raising this issue. A similar question was asked here https://github.com/pwlin/cordova-plugin-file-opener2/issues/92. for iOS you can omit it, but not for android, but there are currently work arounds, as suggested by @cmartin81. I'm going to close this issue as a duplicate of 92, but will keep 92 open and label it as an enhancement for the future.

**Closed by shnist** 2018-12-13 11:02 UTC
