### ISSUE TITLE
Open method doesn't show App list in Windows 10.

### ISSUE THREAD

**Issue by chvvrajesh** [pwlin/cordova-plugin-file-opener2#154] opened 2017-07-24 06:30 UTC
Open function doesn't show list of compatible apps can be used to open the particular file in Windows 10. It just returns the success call back. 

I'm trying to open the tiff/tif image with the Open function. Open function returns with the success callback.  To resolve this error I've to manually(by checking always open with) set the default application as Photos(default app) to open the tiff/tif images. 

Is this a know bug ? or Am I missing something ?

**Update:**
I've updated the **fileOpener2Proxy.js** to set the **displayApplicationPicker** to true so that it shows the list of applications. But even after selecting the "Always use this app to open *** file" this setting is not persisted.

var options = new Windows.System.LauncherOptions();
**options.displayApplicationPicker = true;**

**Question:**
Why plugin failed to open the tiff/tif file using the anyone of the app when we have multiple apps to open the same file ?

**Comment by pwlin** [comment] 2017-07-24 11:50
Can you please be more clear what the problem is? Does the `open` function actually open the file?

**Comment by shnist** [comment] 2018-12-11 17:38
hi @chvvrajesh, thanks for raising this issue. As the issue is over a year old now I'm going to close it. If you still require assistance please feel free to reopen the issue.

**Closed by shnist** 2018-12-11 17:38 UTC
