### ISSUE TITLE
Android 6+

### ISSUE THREAD

**Issue by fishme** [pwlin/cordova-plugin-file-opener2#184] opened 2017-12-01 11:05 UTC
I can't open files with Android 6+, I added also as described the permission  "REQUEST_INSTALL_PACKAGES"

and get this issue in the log
`
E/PluginManager: Uncaught exception from plugin
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                     at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                     at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                     at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                                     at io.github.pwlin.cordova.plugins.fileopener2.FileOpener2._open(FileOpener2.java:110)
                                                                     at io.github.pwlin.cordova.plugins.fileopener2.FileOpener2.execute(FileOpener2.java:67)
                                                                     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                                                                     at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
                                                                     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
                                                                     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
                                                                     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                     at android.os.HandlerThread.run(HandlerThread.java:65)
`
<img width="1606" alt="screen shot 2017-12-01 at 11 53 00" src="https://user-images.githubusercontent.com/11426/33479680-4072aac2-d68e-11e7-94df-c9d241fbd026.png">

any ideas?
Plugin Version: 2.0.19
Version: Android 6.0.1 and 8.0.0
Phone: Nexus 5X

**Comment by fishme** [comment] 2017-12-01 12:30
ok is now working but the solution I don't like maybe there is another way
I had to add in the manifest
`
<provider android:authorities="${applicationId}.opener.provider" android:exported="false" android:grantUriPermissions="true" android:name="io.github.pwlin.cordova.plugins.fileopener2.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/opener_paths" />
        </provider>
`

**Comment by shnist** [comment] 2018-12-12 13:36
hi @fishme, thanks for raising this issue. These fixes made their way into version 2.1.0, so going to close this issue now. Feel free to reopen if the issue is unresolved.

**Closed by shnist** 2018-12-12 13:36 UTC
