### ISSUE TITLE
Migrating to Target 30(Android Q) , plugin is not working

### ISSUE THREAD

**Issue by surabhi2789** [pwlin/cordova-plugin-file-opener2#311] opened 2020-10-28 11:57 UTC
On Migrating to target 30 and making requestlegacy false plugin stopped working.
Please provide support for same.

**Comment by WuglyakBolgoink** [comment] 2020-11-18 14:36
@surabhi2789 yre u installed cordova-plugin-androidx-adapter plugin?

which cordova, cordova-{platforms} versions you have?

this is not enough information

**Comment by cinnamon-doge** [comment] 2021-05-05 07:55
At the moment the plugin seems to need requestlegacy=true to function on Android 11 devices. However, according to Google, requestlegacy is not a solution starting today (May 5 2021):

> We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of one or more of your app bundles or APKs.
> 
> Developers with apps on devices running Android 11+ must use scoped storage to give users better access control over their device storage. To release your app on Android 11 or newer after 5 May, you must either:
> 
> Update your app to use more privacy-friendly best practices, such as the storage access framework or Media Store API
> Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from 5 May
> Remove the All files access permission from your app entirely
> For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.
> 
> Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.

**Comment by shnist** [comment] 2023-01-31 11:31
Duplicate of #310

**Closed by shnist** 2023-01-31 11:31 UTC
