### ISSUE TITLE
iOS dialog location

### ISSUE THREAD

**Issue by hazem-tamimi** [pwlin/cordova-plugin-file-opener2#67] opened 2016-04-26 06:14 UTC
Hello,
Is there a way to set the dialog location for iOS on screen ?

**Comment by andreluizbellon** [comment] 2016-05-04 18:11
+1

**Comment by VincentRoth** [comment] 2016-06-30 08:30
Hello, I am also looking for these feature.

You can use my branch https://github.com/VincentRoth/cordova-plugin-file-opener2
I add a new parameter to position the dialog.

I also create a pull request to the original repository.

**Comment by earnaz** [comment] 2016-11-18 12:35
+1. I need this feature.
Merge request: #72

**Comment by Qsaws** [comment] 2019-10-24 14:01
So any news on this? I have pretty much the same issue as #145 "showOpenWithDialog" works on iphones but not on ipads.

**Comment by shnist** [comment] 2019-10-29 13:06
hi @Qsaws, there was a PR to add this, but unfortunately it was no longer compatible with the codebase (the PR had been open for some time and the codebase had moved on since then). I don't have time to actively develop new features for this plugin, but always happy to review and accept new pull requests.

**Comment by ucsbricks** [comment] 2020-04-03 14:45
I have added a pull request #290 to fix this issue for the current code base. The changes are based on the code @shnist provided some time ago. I could successfully run it on some iPads w/ iOS 11.x to iPadOS 13.4. @pwlin could you please review my code and merge the pull request? Thanks.

**Comment by ucsbricks** [comment] 2020-04-27 14:59
@pwlin @shnist any plans on merging my pull request #290 to finally fix this issue?

**Comment by pwlin** [comment] 2020-05-03 22:30
@ucsbricks I have merged your changes. Can you please test if the issue is fixed now?

**Comment by ucsbricks** [comment] 2020-05-04 08:19
@pwlin thanks for merging. I can confirm it’s fixed.
_Tested on iPad Pro 9.7", iPadOS 13.4.1_

**Comment by ucsbricks** [comment] 2020-05-04 09:15
@shnist could you please consider to release recent changes as v3.0.1?

**Comment by pwlin** [comment] 2020-05-04 10:19
@ucsbricks I pushed cordova-plugin-file-opener2@3.0.1 to npm. Can you please check if it's ok? thanks

**Comment by ucsbricks** [comment] 2020-05-04 12:20
@pwlin yes, it’s ok. Thanks!

**Comment by ucsbricks** [comment] 2020-05-14 07:51
@pwlin please close the issue. Thanks.

**Closed** 2020-05-14 09:08 UTC
Labels: enhancement, ios
