### ISSUE TITLE
Values in Android Manifest get removed. version 2.2.0

### ISSUE THREAD

**Issue by newuser44** [pwlin/cordova-plugin-file-opener2#264] opened 2019-06-28 22:09 UTC
### Expected Behaviour
After building, would expect file to be open.  
This problem seems to stem from another plugin either firebase or cordova-android-support-gradle-release.  
Android is added and plugins are pulling in.  
Manifest looks normal, but more has this line is in the Manifest file. 
 
 <provider android:authorities="${applicationId}.opener.provider" android:exported="false" android:grantUriPermissions="true" android:name="io.github.pwlin.cordova.plugins.fileopener2.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/opener_paths" />
        </provider>

But then when I build.  This provider is removed.  
Then File opener does not work.  

### Actual Behaviour

After a build Manifest File is missing a provider. 
Can not open a file. 

### Reproduce Scenario (including but not limited to)
See above. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
Not sure this matters.   Android 8.  Samsung S7. 

#### Cordova CLI info

    cordova info

Here is the output:
Collecting Data...

Node version: v6.16.0

Cordova version: 7.0.1

Config.xml file:

<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="7" id="com.app.test" ios-CFBundleVersion="1.1" version="1.1" xmlns="http://www.w3.org/ns/widgets" xmlns:android="schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>App Name</name>
    <description>
       App Name
    </description>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="CordovaWebViewEngine" value="CDVUIWebViewEngine" />
    <platform name="android">
        <resource-file src="google-services.json" target="google-services.json" />
        <allow-intent href="market:*" />
        <preference name="ShowSplashScreen" value="true" />
        <preference name="SplashScreenDelay" value="18000" />
        <preference name="SplashShowOnlyFirstTime" value="false" />
        <preference name="android-minSdkVersion" value="22" />
        <preference name="android-targetSdkVersion" value="27" />
        <preference name="loadUrlTimeoutValue" value="700000" />
        <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" />
        </edit-config>
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-anydpi-v26/ic_launcher.xml" target="res/mipmap-anydpi-v26/ic_launcher.xml" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-anydpi-v26/ic_launcher_round.xml" target="res/mipmap-anydpi-v26/ic_launcher_round.xml" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-hdpi/ic_launcher.png" target="res/mipmap-hdpi/ic_launcher.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-hdpi/ic_launcher_background.png" target="res/mipmap-hdpi/ic_launcher_background.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-hdpi/ic_launcher_foreground.png" target="res/mipmap-hdpi/ic_launcher_foreground.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-hdpi/ic_launcher_round.png" target="res/mipmap-hdpi/ic_launcher_round.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-mdpi/ic_launcher.png" target="res/mipmap-mdpi/ic_launcher.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-mdpi/ic_launcher_background.png" target="res/mipmap-mdpi/ic_launcher_background.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-mdpi/ic_launcher_foreground.png" target="res/mipmap-mdpi/ic_launcher_foreground.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-mdpi/ic_launcher_round.png" target="res/mipmap-mdpi/ic_launcher_round.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xhdpi/ic_launcher.png" target="res/mipmap-xhdpi/ic_launcher.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xhdpi/ic_launcher_background.png" target="res/mipmap-xhdpi/ic_launcher_background.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xhdpi/ic_launcher_foreground.png" target="res/mipmap-xhdpi/ic_launcher_foreground.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xhdpi/ic_launcher_round.png" target="res/mipmap-xhdpi/ic_launcher_round.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xxhdpi/ic_launcher.png" target="res/mipmap-xxhdpi/ic_launcher.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xxhdpi/ic_launcher_background.png" target="res/mipmap-xxhdpi/ic_launcher_background.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xxhdpi/ic_launcher_foreground.png" target="res/mipmap-xxhdpi/ic_launcher_foreground.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xxhdpi/ic_launcher_round.png" target="res/mipmap-xxhdpi/ic_launcher_round.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xxxhdpi/ic_launcher.png" target="res/mipmap-xxxhdpi/ic_launcher.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xxxhdpi/ic_launcher_background.png" target="res/mipmap-xxxhdpi/ic_launcher_background.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xxxhdpi/ic_launcher_foreground.png" target="res/mipmap-xxxhdpi/ic_launcher_foreground.png" />
        <resource-file src="./resources/app/icons/pay/android/res/mipmap-xxxhdpi/ic_launcher_round.png" target="res/mipmap-xxxhdpi/ic_launcher_round.png" />
        <splash density="land-ldpi" src="./resources/app/screens/android/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="./resources/app/screens/android/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="./resources/app/screens/android/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="./resources/app/screens/android/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="./resources/app/screens/android/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="./resources/app/screens/android/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="./resources/app/screens/android/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="./resources/app/screens/android/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="./resources/app/screens/android/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="./resources/app/screens/android/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="./resources/app/screens/android/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="./resources/app/screens/android/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="SplashShowOnlyFirstTime" value="false" />
        <preference name="SplashScreen" value="screen" />
        <preference name="DisallowOverscroll" value="true" />
        <preference name="SplashScreenDelay" value="12000" />
        <icon height="40" platform="ios" src="./resources/app/icons/pay/ios/iPhone/Notification-40x40.png" width="40" />
        <icon height="60" platform="ios" src="./resources/app/icons/pay/ios/iPhone/Notification-60x60.png" width="60" />
        <icon height="58" platform="ios" src="./resources/app/icons/pay/ios/iPhone/Settings-58x58.png" width="58" />
        <icon height="87" platform="ios" src="./resources/app/icons/pay/ios/iPhone/Settings-87x87.png" width="87" />
        <icon height="80" platform="ios" src="./resources/app/icons/pay/ios/iPhone/Spotlight-80x80.png" width="80" />
        <icon height="120" platform="ios" src="./resources/app/icons/pay/ios/iPhone/Spotlight-120x120.png" width="120" />
        <icon height="180" platform="ios" src="./resources/app/icons/pay/ios/iPhone/iPhone-180x180.png" width="180" />
        <icon height="180" platform="ios" src="./resources/app/icons/pay/ios/iPhone/iPhone-180x180.png" width="180" />
        <icon height="152" platform="ios" src="./resources/app/icons/pay/ios/iPad/iPadMini-152x152.png" width="152" />
        <icon height="167" platform="ios" src="./resources/app/icons/pay/ios/iPad/iPadPro-167x167.png" width="167" />
        <icon height="1024" platform="ios" src="./resources/app/icons/pay/ios/iPad/AppStore-1024x1024.png" width="1024" />
        <splash height="1136" platform="ios" src="./resources/app/screens/ios/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" platform="ios" src="./resources/app/screens/ios/Default-750@2x~iphone6-portrait.png" width="750" />
        <splash height="750" platform="ios" src="./resources/app/screens/ios/Default-750@2x~iphone6-landscape.png" width="1334" />
        <splash height="2208" platform="ios" src="./resources/app/screens/ios/Default-736h.png" width="1242" />
        <splash height="1242" platform="ios" src="./resources/app/screens/ios/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" platform="ios" src="./resources/app/screens/ios/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="768" platform="ios" src="./resources/app/screens/ios/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" platform="ios" src="./resources/app/screens/ios/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1024" platform="ios" src="./resources/app/screens/ios/Default-Portrait~ipad.png" width="768" />
        <splash height="1500" platform="ios" src="./resources/app/screens/ios/Default~ipad.png" width="208" />
        <splash height="960" platform="ios" src="./resources/app/screens/ios/Default@2x~iphone.png" width="640" />
        <splash height="480" platform="ios" src="./resources/app/screens/ios/Default~iphone.png" width="320" />
    </platform>
    <edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
        <string />
    </edit-config>
    <engine name="android" spec="~6.4.0" />
    <engine name="browser" spec="~4.1.0" />
    <engine name="ios" spec="4.5.5" />
    <plugin name="cordova-android-support-gradle-release" spec="~1.4.4">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-android-fingerprint-auth" spec="^1.4.4" />
    <plugin name="cordova-plugin-device" spec="^1.1.7" />
    <plugin name="cordova-plugin-file" spec="~6.0.1" />
    <plugin name="cordova-plugin-file-opener2" spec="~2.2.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-firebase" spec="~2.0.3" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.1" />
    <plugin name="cordova-plugin-ios-keychain" spec="^3.0.1" />
    <plugin name="cordova-plugin-nativestorage" spec="^2.3.2" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-touch-id" spec="^3.3.1">
        <variable name="FACEID_USAGE_DESCRIPTION" value=" " />
    </plugin>
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.4.1">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.1+" />
    </plugin>
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
</widget>

Plugins:

cordova-android-support-gradle-release,cordova-plugin-android-fingerprint-auth,cordova-plugin-device,cordova-plugin-file,cordova-plugin-file-opener2,cordova-plugin-firebase,cordova-plugin-geolocation,cordova-plugin-ios-keychain,cordova-plugin-nativestorage,cordova-plugin-network-information,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-touch-id,cordova-plugin-whitelist,cordova-plugin-x-socialsharing,es6-promise-plugin,ionic-plugin-keyboard

Error retrieving Android platform information:
Android SDK is not set up properly. Make sure that the Android SDK 'tools' and 'platform-tools' directories are in the PATH variable.

Error: android: Command failed with exit code ENOENT

#### Plugin version

    cordova plugin version | grep cordova-plugin-file-opener2

Here is the output:

cordova-plugin-file-opener2 2.2.0 "File Opener2"

**Comment by shnist** [comment] 2019-07-08 14:33
hi @newuser44, thanks for raising this issue. Is this related to the other issue that you raised earlier? https://github.com/pwlin/cordova-plugin-file-opener2/issues/259

**Comment by newuser44** [comment] 2019-07-15 14:31
Yes it looks like it is.  It seems to be related to the cordova-plugin-firebase  plugin.  When adding android back in, some order of plugins to be installed is followed.  Seems like cordova-plugin-firebase is one of the last and overrides some values in android manifest.  I haven't tested this theory.

**Comment by shnist** [comment] 2019-10-16 16:17
@newuser44 closing this ticket as a duplicate of #215. It seems to be the same issue. The plugin makes changes to the Android manifest xml file and if your config.xml also attempts to make changes then there is a clash and this error occurs. Looking into a fix now.

**Closed by shnist** 2019-10-16 16:17 UTC
