### ISSUE TITLE
Not working lastest vesion

### ISSUE THREAD

**Issue by videmort** [pwlin/cordova-plugin-file-opener2#237] opened 2018-12-12 23:29 UTC
Cordova versión 8.1.2
Cordova-ios version 4.5.5

The following build commands failed:
	CompileC /Users/local/Library/Developer/Xcode/DerivedData/MyApp-bpoxmbxcevnlwihgrvkjufhiwmkc/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/armv7/FileOpener2.o MyApp/Plugins/cordova-plugin-file-opener2/FileOpener2.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by shnist** [comment] 2018-12-13 09:46
hi @videmort thanks for raising this issue. I'm assuming this is a duplicate of https://github.com/pwlin/cordova-plugin-file-opener2/issues/236? If so let's keep the conversation on that thread and I'll close this as a duplicate.

**Comment by umeshShindepatil** [comment] 2018-12-13 11:49
Hi @shnist 
Getting error for android build - Error - A plugin you are using requires a preference: ANDROID_SUPPORT_V4_VERSION.

below code is in my config -
<gap:plugin name="cordova-plugin-file-opener2" source="npm">

plz help.
Thanks!

**Comment by shnist** [comment] 2018-12-13 11:52
hi @umeshShindepatil, the issue you are experiencing is not related to what @videmort has raised. I would be happy to help you, but it helps me if you could raise this as a separate issue. This helps to make sure that your issue doesn't get lost in the thread of something else.

**Closed** 2018-12-13 14:30 UTC
