### ISSUE TITLE
In Android 7 and higher versions, file.opener can't normally open the APK file

### ISSUE THREAD

**Issue by l-hwen** [pwlin/cordova-plugin-file-opener2#183] opened 2017-11-30 08:53 UTC
Error openening file file:///storage/emulated/0/Android/data/io.ionic.starter/files/MyCloud/HelloWorld.apk exposed beyond app through Intent.getData()  
Show no permissions

**Comment by veronicabend** [comment] 2018-01-10 16:37
Did you get any solution for this? I am experiencing the same problem. Thanks!

**Comment by FinlayDaG33k** [comment] 2018-02-17 17:48
I am experiencing this issue as well
Android 8.0 using the latest code here on the git

**Comment by shnist** [comment] 2018-12-21 12:40
hi @l-hwen, thanks for raising this issue and sorry that no one got back to you. There were some fixes around opening APK files that landed in version `2.1.0`. If you can please update to the latest version and see if the issue is resolved for you.

**Comment by shnist** [comment] 2019-02-12 17:16
closing this ticket due to inactivity. I believe the issue was resolved in `2.1.0` anyway. Please feel free to reopen if you still require assistance.

**Closed by shnist** 2019-02-12 17:16 UTC
Labels: android, bug

**Comment by 1106991880** [comment] 2019-04-28 07:57
i am sad , 提示：  file:///storage/emulated/0/test.txt exposed beyond app through Intent.getData()
